<?php if ($column == 'id'): ?>
	<?= $item->getId() ?>
<?php elseif ($column == 'dock'): ?>
	<?php if ($dock = $item->getDock()): ?>
		<?= $dock->getName() ?>
	<?php else: ?>
		N/A
	<?php endif ?>
<?php elseif ($column == 'actions'): ?>
	<?php if ($dock = $item->getDock()): ?>
		<a href="<?= $this->url('app/bicycles/checkout', ['bike-id' => $item->getId()]) ?>">Check-Out</a>
	<?php else: ?>
		<a href="<?= $this->url('app/bicycles/checkin', ['bike-id' => $item->getId()]) ?>">Check-In</a>
	<?php endif ?>
	| <a href="<?= $this->url('app/bicycles/history', ['bike-id' => $item->getId()]) ?>">History</a>
	<?php if ($item->isLocked()): ?>
		| <a href="<?= $this->url('app/bicycles/lock', ['bike-id' => $item->getId()]) ?>">Unlock</a>
	<?php else: ?>
		| <a href="<?= $this->url('app/bicycles/lock', ['bike-id' => $item->getId()]) ?>">Lock</a>
	<?php endif ?>
<?php endif ?>
