<?php if ($column == 'id'): ?>
	<?= $item->getId() ?>
<?php elseif ($column == 'dock'): ?>
	<?php if ($dock = $item->getDock()): ?>
		<?= $dock->getName() ?>
		<?php if ($dock->isLocked()): ?>
			( Locked ) 
		<?php endif ?>
	<?php else: ?>
		N/A
	<?php endif ?>
<?php elseif ($column == 'data'): ?>
	<a href="<?= $this->url('app/gps/bike', ['bike-id' => $item->getId()]) ?>">GPS</a> |
	<a href="<?= $this->url('app/bicycles/history', ['bike-id' => $item->getId()]) ?>">History</a>
<?php elseif ($column == 'actions'): ?>
	<?php if ($dock = $item->getDock()): ?>
		<?php if (!$item->isLocked() && !$dock->isLocked()): ?>
			<a href="<?= $this->url('app/bicycles/checkout', ['bike-id' => $item->getId()]) ?>">Check-Out</a> |
		<?php endif ?>
	<?php else: ?>
		<a href="<?= $this->url('app/bicycles/checkin', ['bike-id' => $item->getId()]) ?>">Check-In</a> |
	<?php endif ?>
	<?php if ($item->isLocked()): ?>
		 <a href="<?= $this->url('app/bicycles/lock', ['bike-id' => $item->getId()]) ?>">Unlock</a>
	<?php else: ?>
		 <a href="<?= $this->url('app/bicycles/lock', ['bike-id' => $item->getId()]) ?>">Lock</a>
	<?php endif ?>
<?php endif ?>
