<?php echo $this->doctype(); ?>
<?php use Libs\Auth\Roles; ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Bike Share') ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/base.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css') ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
	<body data-spy="scroll" data-target="#sidebar">
        <nav class="navbar navbar-inverse navbar-fixed-top banner" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('app') ?>">
                        <img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;Bike Share
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="<?= $this->url('app') ?>">Home</a>
                        </li>
						<?php if ($this->isAllowed(array(Roles::ROLE_ADMIN, Roles::ROLE_VIEW, Roles::ROLE_GUEST))): ?>
							<li class="dropdown">
								<a href="<?= $this->url('app/docks') ?>">Docks</a>
							</li>
						<?php endif; ?>
					</ul>
					<ul class="nav navbar-nav pull-right">
						<li>
							<?php if (!$this->auth()): ?>
								<a href="<?= $this->url('zfcuser/login') ?>">Login</a>
							<?php else: ?>
								<a href="<?= $this->url('zfcuser/logout') ?>">Logout</a>
							<?php endif; ?>
						</li>
                    </ul>
                </div>
            </div>
        </nav>
		<div class="container">
			<div class="flash-messages">
				<?= $this->flash()->render('info', array('Alert--info')) ?>
				<?= $this->flash()->render('warning', array('Alert--warning')) ?>
				<?= $this->flash()->render('error', array('Alert--error')) ?>
				<?= $this->flash()->render('success', array('Alert--success')) ?>
			</div>
			<div class="clearfix">
				<?= $content ?>
			</div>
			<hr>
            <footer class="bs-footer">
                <p>COMS 409, Fall 2014. Iowa State University. </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
		<script>
			$('#sidebar').affix({
				offset: {
					top: function () {
						var offsetTop      = $('#sidebar').offset().top
						var sideBarMargin  = parseInt($('#sidebar').children(0).css('margin-top'), 10)
						var navOuterHeight = $('.banner').height()

						return (this.top = offsetTop - navOuterHeight - sideBarMargin)
					}
					, bottom: function () {
						return (this.bottom = $('.bs-footer').outerHeight(true))
					}
				}
			})
		</script>
    </body>
</html>
