<h1>Bike GPS Data</h1>

<table class="gray full-width">
	<tr>
		<th>Date</th>
		<th>Latitude</th>
		<th>Longitude</th>
	</tr>
	<?php $count = 0 ?>
	<?php foreach ($bike->getCheckOuts() as $co): ?>
		<?php foreach ($co->getGpsData() as $gps): ?>
			<tr>
				<td><?= $gps->getTime(true) ?></td>
				<td><?= $gps->getLatitude() ?></td>
				<td><?= $gps->getLongitude() ?></td
			</tr>
			<?php $count++ ?>
		<?php endforeach ?>
	<?php endforeach ?>
	<?php if (!$count): ?>
		<tr>
			<td colspan="3">There is no gps data for this bicycle</td>
		</tr>
	<?php endif ?>
</table>