routes:
    app:
        type: 'Literal'
        options:
            route: '/'
            defaults: {controller: 'App:Index', action: 'index'}
        may_terminate: true
        child_routes:
            user:
                type: 'Segment'
                options:
                    route: 'user[/:user-id]'
                    defaults: {controller: 'App:User', action: 'view'}
                may_terminate: true
                child_routes:
                    edit:
                        type: 'Literal'
                        options:
                            route: '/edit'
                            defaults: {action: 'edit'}
            docks:
                type: 'Literal'
                options:
                    route: 'docks'
                    defaults: {controller: 'App:Dock'}
                may_terminate: true
