routes:
    app:
        type: 'Literal'
        options:
            route: '/'
            defaults: {controller: 'App:Index', action: 'index'}
        may_terminate: true
        child_routes:
            user:
                type: 'Segment'
                options:
                    route: 'user[/:user-id]'
                    defaults: {controller: 'App:User', action: 'view'}
                may_terminate: true
                child_routes:
                    edit:
                        type: 'Literal'
                        options:
                            route: '/edit'
                            defaults: {action: 'edit'}
            fees:
                type: 'Literal'
                options:
                    route: 'fees'
                    defaults: {controller: 'App:Fee'}
                may_terminate: true
            docks:
                type: 'Literal'
                options:
                    route: 'docks'
                    defaults: {controller: 'App:Dock'}
                may_terminate: true
            bicycles:
                type: 'Literal'
                options:
                    route: 'bicycles'
                    defaults: {controller: 'App:Bicycle'}
                may_terminate: true
                child_routes:
                    checkout:
                        type: 'Segment'
                        options:
                            route: '/:bike-id/checkout'
                            defaults: {action: 'checkout'}
                        may_terminate: true
                    checkin:
                        type: 'Segment'
                        options:
                            route: '/:bike-id/checkin'
                            defaults: {action: 'checkin'}
                        may_terminate: true
                    lock:
                        type: 'Segment'
                        options:
                            route: '/:bike-id/lock'
                            defaults: {action: 'lock'}
                        may_terminate: true
                    lockall:
                        type: 'Segment'
                        options:
                            route: '/:bike-id/lockall'
                            defaults: {action: 'lockall'}
                        may_terminate: true
                    history:
                        type: 'Segment'
                        options:
                            route: '/:bike-id/history'
                            defaults: {action: 'history'}
                        may_terminate: true
